import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { OptionProvider } from "@/providers/optionContext";
import DateProvider from "@/providers/dateProvider";
import ShowDatesProvider from "@/providers/showDateProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-20 py-10`}>
        <Toaster position="top-center" />
        <DateProvider>
          <ShowDatesProvider>
            <OptionProvider>{children}</OptionProvider>
          </ShowDatesProvider>
        </DateProvider>
      </body>
    </html>
  );
}
