[, "animate-inputError"];
//colors
[
  "bg-basic-default",
  "bg-basic-happy",
  "bg-basic-sad",
  "bg-basic-sad",
  "bg-basic-energetic:",
  "bg-basic-sick",
  "bg-basic-neutral",
  "bg-basic-angry",
  "bg-basic-well",
  "bg-basic-cold",
  "bg-basic-headache",
  "bg-basic-hangover",
  "bg-basic-fog",
  "bg-basic-none",
  "bg-basic-low",
  "bg-basic-medium",
  "bg-basic-high",
  "bg-basic-extreme",
];
